<div class="col-lg-12">
    <div class="list-group">
        <form action="" method="post"> 
            <div class="form-group">
                <label for="formExempleInputname">username</label>
                <input type="text" class="form-controle" name="username" value="<?=$username?>" id ="formGroupExempleusername" >
            </div>
            <div class="form-group">
                <label for="formExempleInputname">firstname</label>
                <input type="text" class="form-controle" name="firstname" value="<?=$firstname?>" id ="formGroupExempleusername" >
            </div>
            <div class="form-group">
                <label for="formExempleInputname">lastname</label>
                <input type="text" class="form-controle" name="lastname" value="<?=$lastname?>" id ="formGroupExempleusername" >
            </div>
            <div class="form-group">
                <label for="formExempleInputemail">adress mail</label>
                <input type="text" class="form-controle" name="email"  value ="<?=$email?>" id ="formGroupExemplemail" >
            </div>
            <div class="form-group">
                <label for="formExempleInputpassword">password</label>
                <input type="text" class="form-controle" name="password"  value ="<?=$password?>" id ="formGroupExemplepassword" >
            </div>
            <div class="form-group">
                <label for="formExempleInputpassword">confirm your password</label>
                <input type="text" class="form-controle" name="confirm"  value ="<?=$confirm?>" id ="formGroupExempleconfirm" >
            </div>
            <div class="form-group">
                <label for="formExempleInputpassword">biographie</label>
                <input type="text" class="form-controle" name="bio"  value ="<?=$bio?>" id ="formGroupExemplebiographie" >
            </div>
            <div class="form-group">
                <label for="formExempleInputpassword">Avatar</label>
                <input type="text" class="form-controle" name="avatar"  value ="<?=$password?>" id ="formGroupExempleavatar" >
            </div>
            <div class="form-group">
                <label for="formExempleInputpassword">role</label>
                <input type="text" class="form-controle" name="role"  value ="<?=$role?>" id ="formGroupExemplerole" >
            </div>
            <div class="form-example">
            <input type="submit" value="Enregistrez">
        </form>
    </div>            

</div>