<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8">
		<title>Projet</title>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
		<style type="text/css">
			img {
				width: 100%;
				margin-bottom: 20px;
			}
		</style>
	</head>
	<body>
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#">Accueil</a></li>
					<li><a href="#">About us</a></li>
					<li><a href="#">contact</a></li>
					<li><a href="#">job</a></li>
					<li><a href="#"></a>Actuality</li>
					<li><a href="../admin/listUser.php">Users</a></li>
					<li><a href="#">Dolor</a></li>
				</ul>
				<form class="navbar-form navbar-right inline-form">
					<div class="form-group">
						<input type="search" class="input-sm form-control" placeholder="Recherche">
						<button type="submit" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-eye-open"></span> Chercher</button>
					</div>
				</form>
			</div>
		</nav>
		<div class="container">
		
			<section class="row">
				
                  <?php include 'tpl/'.$vue ;?>
				
				
			</section>
			<hr/>
			<footer class="row">
				<address>
					<strong>3W Academy</strong><br>
					46, rue René Clair<br>
					75018 Paris<br>
					<abbr title="Téléphone">Tel:</abbr> +33 1 40 58 19 72
				</address>
			</footer>
		</div>
  </body>
</html>