<h2>lists users</h2>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">username</th>
      <th scope="col">firstname</th>
      <th scope="col">lastname</th>
      <th scope="col">mail</th>
      <th scope="col">password</th>
      <th scope="col">bio</th>
      <th scope="col">avatar</th>
      <th scope="col">created_date</th>
      <th scope="col">role</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"></th>
      <td><?=$username?></td>
      <td><?=$firstname?></td>
      <td><?=$lastname?></td>
      <td><?=$email?></td>
      <td><?=$password?></td>
      <td><?=$bio?></td>
      <td><?=$avatar?></td>
      <td><?=$created_date?></td>
      <td><?=$role?></td>
    </tr>
  </tbody>

</table>