<h2>login</h2>
<form action="action_page.php" method="post">

  <div class="container">
    <div>
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" value="<?=$username?>" id ="formGroupExempleusername" >
    </div>
    <div>
    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" value ="<?=$password?>" id ="formGroupExempleavatar">
   </div>
   <div>
    <button type="submit">Login</button>
    <div>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
    </div>
  </div>
  <div class="container" style="background-color:#f1f1f1">
    <button type="button" class="cancelbtn">Cancel</button>
    <span class="psw">Forgot <a href="#">password?</a></span>
  </div>
</form> 